name = "Polisher"
author = "devinreal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ee83f25f0187fc29a77e29c808df3ff87a22acd8007c8b675194c8fee84c1fa"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
