name = "Polisher"
author = "devinreal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b3c4f74e8bcd565f3b2bcab6aa4ecbd7b6d8fa7ef157d6dccf14ffbc70b56cc"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
