name = "Polisher"
author = "devinreal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0df212015c1fc6e36d626f25b17e0ef9b2632ee23ea252acdbffb5a474e3d5c4"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
