name = "Polisher"
author = "devinreal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7bdea25585ffeb961fcaa7dc55623d49cc33b813f09c7505d350de78027b452"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
