name = "Polisher"
author = "devinreal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e4e5901e32e947c0cb397cb50de96b2aa7ebd12a30516cdbe2f711766bffa01"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
