name = "Polisher"
author = "devinreal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "295c1baf35dd1fc0cf989688c5f4824106c6a9e11f3ba1ca13f4b434b7484e61"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
