name = "Polisher"
author = "devinreal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b123ded8deeabd5b43de6435106de46b80b3583c98d21911a26a8137aac4271"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
